// Package config handles labwatch agent configuration.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// Config holds all agent configuration.
type Config struct {
	// API endpoint URL
	APIEndpoint string `yaml:"api_endpoint"`

	// Agent authentication token (obtained during registration)
	Token string `yaml:"token"`

	// Admin secret (used only during registration)
	AdminSecret string `yaml:"admin_secret,omitempty"`

	// Collection interval
	Interval time.Duration `yaml:"interval"`

	// Lab identifier (auto-generated on first run)
	LabID string `yaml:"lab_id"`

	// Hostname override (defaults to os.Hostname)
	Hostname string `yaml:"hostname"`

	// Docker collector settings
	Docker DockerConfig `yaml:"docker"`

	// GPU collector settings
	GPU GPUConfig `yaml:"gpu"`

	// S.M.A.R.T. disk health settings
	SMART SMARTConfig `yaml:"smart"`

	// ZFS pool health settings
	ZFS ZFSConfig `yaml:"zfs"`

	// Log collection settings
	Logs LogsConfig `yaml:"logs"`

	// Services to monitor
	Services []ServiceConfig `yaml:"services"`
}

// DockerConfig controls Docker container monitoring.
type DockerConfig struct {
	Enabled bool   `yaml:"enabled"`
	Socket  string `yaml:"socket"`
}

// GPUConfig controls NVIDIA GPU monitoring.
type GPUConfig struct {
	Enabled bool `yaml:"enabled"`
}

// SMARTConfig controls S.M.A.R.T. disk health collection.
// Requires smartctl (smartmontools) installed and readable by the agent user.
type SMARTConfig struct {
	Enabled bool `yaml:"enabled"`
}

// ZFSConfig controls ZFS pool health collection.
// Requires zpool (ZFS utilities) installed.
type ZFSConfig struct {
	Enabled bool `yaml:"enabled"`
}

// LogsConfig controls log collection and shipping.
type LogsConfig struct {
	Enabled         bool     `yaml:"enabled"`
	Journald        bool     `yaml:"journald"`
	Docker          bool     `yaml:"docker"`
	Files           []string `yaml:"files"`
	LevelFilter     string   `yaml:"level_filter"`
	MaxLinesPerPush int      `yaml:"max_lines_per_push"`
	DockerSocket    string   `yaml:"docker_socket"`
}

// ServiceConfig defines a service to monitor.
type ServiceConfig struct {
	Name     string `yaml:"name"`
	Type     string `yaml:"type"`     // "http", "tcp", "systemd"
	Endpoint string `yaml:"endpoint"` // URL for http, host:port for tcp, unit name for systemd
	Timeout  string `yaml:"timeout"`
}

// Defaults returns a config with sensible defaults.
func Defaults() *Config {
	hostname, _ := os.Hostname()
	return &Config{
		APIEndpoint: "https://labwatch.dev/api/v1",
		Interval:    60 * time.Second,
		Hostname:    hostname,
		Docker: DockerConfig{
			Enabled: true,
			Socket:  "/var/run/docker.sock",
		},
		GPU: GPUConfig{
			Enabled: true,
		},
		SMART: SMARTConfig{
			Enabled: true,
		},
		ZFS: ZFSConfig{
			Enabled: true,
		},
		Logs: LogsConfig{
			Enabled:         false,
			Journald:        true,
			Docker:          true,
			LevelFilter:     "warn",
			MaxLinesPerPush: 100,
		},
	}
}

// Load reads config from a YAML file, falling back to defaults.
func Load(path string) (*Config, error) {
	cfg := Defaults()

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			// No config file — use defaults
			return cfg, nil
		}
		return nil, fmt.Errorf("reading config: %w", err)
	}

	if err := yaml.Unmarshal(data, cfg); err != nil {
		return nil, fmt.Errorf("parsing config: %w", err)
	}

	if cfg.Interval < 10*time.Second {
		cfg.Interval = 10 * time.Second
	}

	return cfg, nil
}

// Write generates a clean, human-readable config file.
func Write(path string, cfg *Config) error {
	content := fmt.Sprintf(`# labwatch agent configuration
# Generated by: labwatch --register

api_endpoint: %s
lab_id: %s
token: %s
hostname: %s
interval: %s

docker:
  enabled: true
  socket: /var/run/docker.sock

gpu:
  enabled: true

smart:
  enabled: true

zfs:
  enabled: true

logs:
  enabled: false
  journald: true
  docker: true
  level_filter: warn
  max_lines_per_push: 100
  # files: []

# Add custom service checks:
# services:
#   - name: my-app
#     type: http
#     endpoint: http://localhost:8080/health
#     timeout: 5s
`, cfg.APIEndpoint, cfg.LabID, cfg.Token, cfg.Hostname, cfg.Interval)

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}

	if err := os.WriteFile(path, []byte(content), 0640); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	return nil
}
